src/login_account/urls.py
from django.urls import path
from django.contrib.auth import views
from . import views

app_name = 'login_account'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),  
    
]

src/objective_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('index/', permanent=True)),  # Redirect root to /index/
    path('index/', include('objective_manager_app.urls')),  # Map /index/ to your app's URLs
]

src/templates/base copy.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="de">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <style>
        /* Add custom styles directly in the HTML or in your styles.css file */
        
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-custom">
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'home_detail' %}active{% endif %}" href="{% url 'home_detail' %}">Home</a>
        </li>
        
        <!-- Strategie Selection Box -->
        {% if request.resolver_match.url_name == 'home_detail' %}
          <li class="nav-item d-flex align-items-center">
            <span class="nav-link" style="padding-right: 0;">Strategie:&nbsp;</span>
            <form method="post" action="{% url 'home_detail' %}" class="d-flex align-items-center" style="margin-bottom: 0;">
              {% csrf_token %}
              <div class="form-group mb-0 flex-grow-1">
                <select id="strategie_auswahl" name="strategie_auswahl" class="form-control full-width-select navbar-select" onchange="this.form.submit();">
                  {% for strategie in strategieen %}
                    <option value="{{ strategie.id }}" data-description="{{ strategie.beschreibung }}" {% if strategie.id == strategie_auswahl.id %}selected{% endif %}>{{ strategie.titel }}</option>
                  {% endfor %}
                </select>
              </div>
            </form>
          </li>
        {% else %}
          <li class="nav-item">
            <span class="nav-link">Strategie:&nbsp;<b>{{ strategie.titel_kurz }}</b></span>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'handlungsfelder_list' %}active{% endif %}" href="{% url 'handlungsfelder_list' %}">Handlungsfelder</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'ziele_list' %}active{% endif %}" href="{% url 'ziele_list' %}">Ziele</a>
        </li>
        {% if request.user|is_in_group:"admins" %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'massnahmen_list' %}active{% endif %}" href="{% url 'massnahmen_list' %}">Massnahmen</a>
          </li>
        {% endif %}
        {% if request.user|is_in_group:"operators" %}
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'plan_records_list' %}active{% endif %}" href="{% url 'plan_records_list' %}">Planung</a>
        </li>
        {% endif %}
        {% if request.user|is_in_group:"admins" %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'personen_list' %}active{% endif %}" href="{% url 'personen_list' %}">Personen</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'organisationen_list' %}active{% endif %}" href="{% url 'organisationen_list' %}">Organisationen</a>
          </li>
        {% endif %}
      </ul>

      <!-- Right-aligned items -->
      <ul class="navbar-nav ms-auto">
        {% if not request.user.is_authenticated %}
          <!-- User is not logged in -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login_account:login' %}">Login</a>
          </li>
        {% else %}
          <!-- User is logged in -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login_account:profile' %}">{{request.user.first_name.0|upper}}{{request.user.last_name.0|upper}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login_account:logout' %}">Logout</a>
          </li>
        {% endif %}
      </ul>
      
    </div>
  </nav>
  <br>

  {% block content %}
  {% endblock %}

  <!-- Footer with version number -->
  <footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
      <span class="text-muted">&copy; Statistisches Amt Basel-Stadt<span style="float:right; font-size: smaller;">v0.0.4 (04.8.2024)</span></span>
    </div>
  </footer>

  {% if messages %}
    <script>
        $(document).ready(function() {
            {% for message in messages %}
                toastr.options = {
                    "closeButton": true,
                    "progressBar": true,
                }
                toastr.success("{{ message|escapejs }}");
            {% endfor %}
        });
    </script>
  {% endif %}
</body>
</html>

src/templates/base.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="de">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <style>
        /* Add custom styles directly in the HTML or in your styles.css file */
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-custom">
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'index'%}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'handlungsfelder_list' %}active{% endif %}" href="{% url 'handlungsfelder_list' %}">Handlungsfelder</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'ziele_list' %}active{% endif %}" href="{% url 'ziele_list' %}">Ziele</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'massnahmen_list' %}active{% endif %}" href="{% url 'massnahmen_list' %}">Massnahmen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'themen_list' %}active{% endif %}" href="{% url 'themen_list' %}">Themen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'kennzahlen_list' %}active{% endif %}" href="{% url 'kennzahlen_list' %}">Kennzahlen</a>
        </li>
        {% if request.user|is_in_group:"operators" %}
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'plan_records_list' %}active{% endif %}" href="{% url 'plan_records_list' %}">Planung</a>
        </li>
        {% endif %}
        {% if request.user|is_in_group:"admins" %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'personen_list' %}active{% endif %}" href="{% url 'personen_list' %}">Personen</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'organisationen_list' %}active{% endif %}" href="{% url 'organisationen_list' %}">Organisationen</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <br>

  {% block content %}
  {% endblock %}

  <!-- Footer with version number -->
  <footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
      <span class="text-muted">&copy; Statistisches Amt Basel-Stadt<span style="float:right; font-size: smaller;">v0.0.9 (13.1.2025)</span></span>
    </div>
  </footer>

  {% if messages %}
    <script>
        $(document).ready(function() {
            {% for message in messages %}
                toastr.options = {
                    "closeButton": true,
                    "progressBar": true,
                }
                toastr.success("{{ message|escapejs }}");
            {% endfor %}
        });
    </script>
  {% endif %}
</body>
</html>